name: main-proxy

services:
  certbot:
    image: certbot/certbot:v5.1.0
    container_name: main-proxy-certbot
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "while true; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"]
    volumes:
      - "certbot-certs:/etc/letsencrypt"
      - "certbot-webroot:/var/www/certbot"
      - "/var/log/letsencrypt:/var/log/letsencrypt"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    depends_on:
      - nginx

  tailscale:
    image: tailscale/tailscale:stable
    container_name: ts-main
    hostname: ts-main
    env_file: "secrets/main.env"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
    volumes:
      - ts-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ports:
      - "443:443"
      - "80:80"

  nginx:
    image: nginx:1.29.2
    container_name: main-proxy-nginx
    restart: unless-stopped
    volumes:
      - "./nginx-conf/:/etc/nginx/conf.d:ro"
      - "certbot-certs:/etc/letsencrypt:ro"
      - "certbot-webroot:/var/www/certbot:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    network_mode: service:tailscale
    depends_on:
      - tailscale

  dozzle:
    image: amir20/dozzle:latest
    container_name: main-proxy-dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=main-proxy
      # ssh-server:10007
      - DOZZLE_REMOTE_AGENT=blackberry-ts-dozzle:7007,dozzle-raspb-server:7007
      - DOZZLE_NO_ANALYTICS=true
    secrets:
      - source: dozzle-users
        target: /data/users.yml
    network_mode: service:tailscale
    depends_on:
      - tailscale

volumes:
  certbot-certs:
    name: "main-proxy-certbot-certs"
    # it is external so the date generated by Make command
    external: true
  dozzle:
    name: "main-proxy-dozzle"
  certbot-webroot:
    name: "main-proxy-certbot-webroot"
  ts-state:
    name: "main-proxy-ts-state"

networks:
  default:
    name: "main-proxy-network"

secrets:
  dozzle-users:
    file: secrets/dozzle-users.yaml
