services:
  certbot:
    image: certbot/certbot:v5.6.0
    container_name: certbot
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      apk add docker-cli;
      while :; do
        certbot renew --deploy-hook "docker exec nginx nginx -s reload 2>/dev/null" --webroot -w /var/www/certbot;
        sleep 12h & wait $${!};
      done'
    volumes:
      - "certbot-certs:/etc/letsencrypt"
      - "certbot-webroot:/var/www/certbot"
      - "/var/log/letsencrypt:/var/log/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    depends_on:
      - nginx

  ssh-server:
    image: linuxserver/openssh-server:10.2_p1-r0-ls226
    container_name: ssh-server
    restart: unless-stopped
    env_file: "./secrets/ssh-auth-key.env"
    environment:
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
      - SHELL_NOLOGIN=true
      - USER_NAME=dummy
    expose:
      # mykpp.online
      - 10000
      # mountainteaband.ru
      - 10001
      # photos.tikhonnnnn.com
      - 10002
      # files.tikhonnnnn.com
      - 10003
      # music.tikhonnnnn.com
      - 10004
      # oss.music.tikhonnnnn.com
      - 10005
      # secrets.tikhonnnnn.com
      - 10006
      # tags.music.tikhonnnnn.com
      - 10007
      # brainz.music.tikhonnnnn.com
      - 10008 
      # discs.tikhonnnnn.com
      - 10009
      # notes.tikhonnnnn.com
      - 10010
    ports:
      # ssh port for reverse tunnels
      # only on ipv4 address so i only put 
      # ipv4 in client configs
      - "56234:2222"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - webnet

  nginx:
    image: nginx:1.31.0
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "certbot-certs:/etc/letsencrypt:ro"
      - "certbot-webroot:/var/www/certbot:ro"
      - "./secrets/main/nginx-htpasswd:/etc/nginx/.htpasswd:ro"
      - "./nginx-contents/:/usr/share/nginx/html:ro"
    ports:
      # No service running on this port, just redirecting to 443
      - "80:80"
      
      # Binding to tcp for http / http2 support
      - "443:443/tcp"
      
      # Binding to udp for quic / http3 support
      - "147.45.159.94:443:443/udp"
      - "[2a03:6f00:a::ce16]:443:443/udp"

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      webnet:
        ipv4_address: 172.18.0.10

  ts-dozzle:
    image: tailscale/tailscale:stable
    container_name: ts-dozzle
    hostname: ts-dozzle-main
    env_file: 
      - "./secrets/headscale.env"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    expose:
      # dozzle
      - "8080"
    networks:
      - webnet
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      # - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=main-proxy
      # ,blueberry-ts-dozzle:7007
      - DOZZLE_REMOTE_AGENT=blackberry-ts-dozzle:7007,apple-ts-dozzle:7007
      - DOZZLE_NO_ANALYTICS=true
    secrets:
      - source: dozzle-users
        target: /data/users.yml
    network_mode: service:ts-dozzle
    depends_on:
      - ts-dozzle
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  watchtower:
    image: nickfedor/watchtower:1
    container_name: watchtower
    env_file: 
      - "./secrets/watchtower.env"
      - "./secrets/proxy.env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --cleanup --remove-volumes --schedule "0 0 4 * * *"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  headscale:
    image: headscale/headscale:0.28.0
    restart: unless-stopped
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    expose:
      - 8080
    ports:
      - "147.45.159.94:3478:3478/udp"
      - "[2a03:6f00:a::ce16]:3478:3478/udp"
    volumes:
      - "headscale-data:/var/lib/headscale"
      - "./headscale/headscale-conf.yaml:/etc/headscale/config.yaml:ro"
      - "./secrets/headscale/:/etc/headscale/secrets:ro"
    command: serve
    healthcheck:
      test: ["CMD", "headscale", "health"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      me.tale.headplane.target: headscale

  headplane:
    image: ghcr.io/tale/headplane:0.6.3
    container_name: headplane
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - "headplane-data:/var/lib/headplane"
      - "./headscale/headplane-conf.yaml:/etc/headplane/config.yaml"
      - "./headscale/headscale-conf.yaml:/etc/headscale/config.yaml:ro"
      - "./secrets/headscale/:/etc/headscale/secrets:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: volume-backup
    restart: unless-stopped
    env_file: "./secrets/main/volume-backup.env"
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '7'
    volumes:
      - "headscale-data:/backup/headscale:ro"
      - "headplane-data:/backup/headplane:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  certbot-certs:
    name: "main-proxy-certbot-certs"
    # it is external so the volume generated by Make command
    external: true
  dozzle:
    name: "main-proxy-dozzle"
  certbot-webroot:
    name: "main-proxy-certbot-webroot"
  ts-dozzle-state:
    name: "main-proxy-ts-dozzle-state"
  headscale-data:
    name: "main-proxy-headscale-data"
  headplane-data:
    name: "main-proxy-headplane-data"

networks:
  default:
    name: "main-proxy-network"
    external: true
  webnet:
    name: "main-proxy-network"
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
        - subnet: fde6:c965:c0b0::/64

secrets:
  dozzle-users:
    file: ./secrets/main/dozzle-users.yaml
