# vim: ft=nginx:

upstream docker-musicbrainz-picard {
	# If the reverse proxy server is not running on the same machine as the
	# Docker container, use the IP of the Docker host here.
	# Make sure to adjust the port according to how port 5800 of the
	# container has been mapped on the host.
	server ssh-server:10008;
}

server {
    listen 443 ssl;
    listen 443 quic;
    listen [::]:443 ssl;
    listen [::]:443 quic;

    server_name brainz.music.tikhonnnnn.com;

    ssl_certificate     /etc/letsencrypt/live/brainz.music.tikhonnnnn.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/brainz.music.tikhonnnnn.com/privkey.pem;

    include /etc/nginx/conf.d/options/options-ssl-nginx.conf;

    proxy_http_version 1.1;
    proxy_set_header   Upgrade    $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_redirect     off;

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

	location / {
		proxy_pass http://docker-musicbrainz-picard;
	}

	location /websockify {
		proxy_pass http://docker-musicbrainz-picard;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_read_timeout 86400;
	}
}
