user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $status $log_level {
        ~^1       "info";
        ~^2       "info";
        ~^3       "info";
        ~^4       "warn";
        ~^5       "error";
        default   "info";
    }
    log_format json escape=json
        '{'
        '"timestamp": "$time_iso8601",'
        '"level":"$log_level",'
        '"pid": "$pid",'
        '"client_ip": "$remote_addr",'
        '"request_id": "$request_id",'
        '"http_method": "$request_method",'
        '"http_path": "$uri",'
        '"protocol": "$server_protocol",'
        '"host": "$host",'
        '"user_agent": "$http_user_agent",'
        '"referer": "$http_referer",'
        '"status_code": $status,'
        '"bytes_sent": $body_bytes_sent,'
        '"request_time_secs": $request_time'
        '}';
    access_log /var/log/nginx/access.log json;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
