# vim: ft=nginx:

server {
    listen 443 ssl;
    listen 443 quic;
    listen [::]:443 ssl;
    listen [::]:443 quic;

    server_name mountainteaband.ru;

    ssl_certificate     /etc/letsencrypt/live/mountainteaband.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mountainteaband.ru/privkey.pem;

    include /etc/nginx/conf.d/options/options-ssl-nginx.conf;

    location / {
        proxy_pass http://ssh-server:10000;
    }
}
