# vim: ft=nginx:

server {
    listen 443 ssl;
    listen 443 quic;
    listen [::]:443 ssl;
    listen [::]:443 quic;

    server_name mykpp.online;

    ssl_certificate     /etc/letsencrypt/live/mykpp.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mykpp.online/privkey.pem;

    include /etc/nginx/conf.d/options/options-ssl-nginx.conf;

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location / {
        proxy_pass http://ssh-server:10001;
    }
}
