# vim: ft=nginx:

server {
    listen 443 ssl;
    listen 443 quic reuseport;
    listen [::]:443 ssl;
    listen [::]:443 quic reuseport;

    server_name tikhonnnnn.com;

    ssl_certificate     /etc/letsencrypt/live/tikhonnnnn.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tikhonnnnn.com/privkey.pem;

    include /etc/nginx/conf.d/options/options-ssl-nginx.conf;

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

    location = /contents {
        root /usr/share/nginx/html;
        try_files /contents.html =404;
    }

    location = /contents/ru {
        root /usr/share/nginx/html;
        try_files /contents-ru.html =404;
    }

    location = /contents/music {
        root /usr/share/nginx/html;
        try_files /contents-music.html =404;
    }

    location = /contents/notes {
        root /usr/share/nginx/html;
        try_files /contents-notes.html =404;
    }

    location = /contents/ru/notes {
        root /usr/share/nginx/html;
        try_files /contents-notes-ru.html =404;
    }

    location = /contents/ru/music {
        root /usr/share/nginx/html;
        try_files /contents-music-ru.html =404;
    }

    location = /contents/style.css {
        root /usr/share/nginx/html;
        try_files /style.css =404;
    }

    location / {
        return 302 https://youtu.be/dQw4w9WgXcQ?si=Cl5EqVYfNU9bkOg6;
    }
}
